server:
  port: 9988
spring:
  application:
    name: consumer
  rabbitmq:
    host: 192.168.31.43
    port: 5672
    virtual-host: /hello
    username: hello
    password: hello
    listener:
      simple:
        prefetch: 1 #每次只能获取一条消息，处理完成才能获取下一个消息
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration